### ISSUE TITLE
php 7.2.1 환경에서요.....

### ISSUE THREAD

**Issue by dmzvillager** [Xvezda/xe-zipdownload-addon#1]
ver 1.0은 작동하는데, ver 1.1은 작동하지않습니다.

**Comment by Xvezda** [comment]
@dmzvillager 개발환경이 7.2.0 이라 업데이트 진행 후에 확인해보겠습니다.

**Comment by Xvezda** [comment]
@dmzvillager 테스트 결과 정상작동 확인했습니다. 
어떤 환경인지, 어떤 증상인지 자세한 설명 부탁드립니다.

XE 1.9.3 + Apache 2.4.29 + PHP 7.2.1 에서 확인했으나 증상이 재현되지 않았습니다.

**Comment by dmzvillager** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=22753726 이미지 프로세서 모듈의 원본저장 설정으로 저장된 이미지의 경우 증상이 나타나는군요.

**Comment by Xvezda** [comment]
@dmzvillager 그러면 해당 모듈이 설치 되어있는지를 검사해서 우회하는 방향으로 패치해보도록 하겠습니다.

**Comment by Xvezda** [comment]
#1 fix de1e6aa

**Comment by dmzvillager** [comment]
감사합니다.
