### ISSUE TITLE
버그는 아니지만 도움이 필요해서 의견을 남겨봅니다.:)

### ISSUE THREAD

**Issue by botserv** [Xvezda/xe-zipdownload-addon#2]
안녕하세요! 그 동안 계속 잘사용하고 있는데요 혹시 
위젯에서도 이 기능을 적용할 수 있는 방법이 있을까요? 

다운로드 랭킹위젯(https://www.xpressengine.com/index.php?mid=download&package_id=20694365)
에 적용할 수 있는 방법이 있으면 참 좋겠어요 -_ㅠ

**Comment by Xvezda** [comment]
@botserv 간단한 수정으로 적용이 가능 할 것 같습니다. 테스트하여 정상작동하면 알려드리겠습니다.

**Comment by Xvezda** [comment]
@botserv 
`/xe/widgets/rank_download/skins/sz_xe/list.html` 파일의 **18번 라인**을

`<!--@if($widget_info->download)--><div class="download"><a href="{getUrl('', 'document_srl',$val->upload_target_srl, 'act', 'zip')}" onClick="return (confirm('다운시 포인트가 차감됩니다'))?true:false">`

코드로 교체하시면 됩니다.

혹시 다른 위젯에 적용하고 싶으신 경우에도, 해당 스킨의 링크를 생성하는 템플릿 구문을 
`{getUrl('', 'document_srl', document_srl 변수, 'act', 'zip')}`
형식처럼 바꿔주시면 됩니다.
